function r = rmse(data,estimate)
%RMSE    calculate the root mean squared error of two data sets
%   RMSE takes in two data objects, the actual data and the estimated data
%   generated by the GP-created expression, and calculates the root mean
%   squared error between them.
%
%   Input Arguments:
%   DATA, ESTIMATE = data to judge the estimate by. Must be same size.
%   
%   Output Arguments:   
%   R = returns the rmse score
%
%   Adapted from: % http://www.mathworks.com/matlabcentral/fileexchange/21383-rmse

%remove nan's from data
I = ~isnan(data) & ~isnan(estimate); 

data = data(I); 
estimate = estimate(I);

r=sqrt(sum((data(:)-estimate(:)).^2)/numel(data));

end